M48
; DRILL file {KiCad 9.0.0} date 2025-10-08T14:33:07-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-10-08T14:33:07-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0945
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1220
%
G90
G05
T1
X4.8583Y-3.9645
X6.8347Y-3.9645
T2
X5.8465Y-2.9763
X5.8465Y-4.9527
M30
